ReferralApp/Models/UserProfileFollowingPeopleViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ReferralApp.Entities;

namespace ReferralApp.Models
{
    public class UserProfileFollowingPeopleViewModel : BaseUserProfileViewModel
    {
        public List<LeaderFollowerRelationship> LeaderFollowerRelationships { get; set; }
    }
}

ReferralApp/Models/UserProfileFollowingReferralListsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ReferralApp.Entities;

namespace ReferralApp.Models
{
    public class UserProfileFollowingReferralListsViewModel : BaseUserProfileViewModel
    {
        public List<ReferralListFollowerRelationship> ReferralListFollowerRelationships { get; set; }
    }
}

ReferralApp/Models/UserProfileFollowingTagsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ReferralApp.Entities;

namespace ReferralApp.Models
{
    public class UserProfileFollowingTagsViewModel : BaseUserProfileViewModel
    {
        public List<TagFollowerRelationship> TagFollowerRelationships { get; set; }
    }
}

ReferralApp/Models/UserProfileViewModel.cs
using ReferralApp.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ReferralApp.Models
{
    public class UserProfileViewModel : BaseUserProfileViewModel
    {
        public ReferralList ReferralList { get; set; }
        public List<Referral> Referrals { get; set; }
        public List<ReferralList> ReferralLists { get; set; }
        public bool NoReferralsLeft { get; set; }
        public bool NoReferralListsLeft { get; set; }
        public SortSelection SortSelectionSelected { get; set; }
        public List<SortSelection> SortSelectionsNotSelected { get; set; }
    }
}

ReferralApp/Controllers/UserProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ReferralApp.Models;
using ReferralApp.Helpers;
using ReferralApp.DAL;
using ReferralApp.Services;
using System.IO;

namespace ReferralApp.Controllers
{
    public class UserProfileController : BaseController
    {
        private UserService _userService;
        private LeaderFollowerRelationshipService _leaderFollowerRelationshipService;
        private ReferralService _referralService;
        private ReferralListService _referralListService;
        private ReferralListFollowerRelationshipService _referralListFollowerRelationshipService;
        private TagFollowerService _tagFollowerService;

        public UserProfileController()
        {
            _userService = new UserService();
            _leaderFollowerRelationshipService = new LeaderFollowerRelationshipService();
            _referralService = new ReferralService();
            _referralListService = new ReferralListService();
            _referralListFollowerRelationshipService = new ReferralListFollowerRelationshipService();
            _tagFollowerService = new TagFollowerService();
        }

        public ActionResult UserProfileHome(UserProfileViewModel viewModel, string userName)
        {
            try
            {
                SetBaseUserProfile(viewModel);
            }
            catch (Exception ex)
            {

            }
            return View(viewModel);
        }

        public ActionResult UserProfileReferrals(UserProfileViewModel viewModel, string sort)
        {
            try
            {
                SetBaseUserProfile(viewModel);
                var sortSelection = ApplicationHtmlHelper.BuildSortSelection(sort);
                viewModel.SortSelectionSelected = sortSelection.SingleOrDefault(s => s.IsSelected);
                viewModel.SortSelectionsNotSelected = sortSelection.Where(s => !s.IsSelected).ToList();
            }
            catch (Exception ex)
            {

            }
            return View(viewModel);
        }

        public ActionResult UserProfileReferralLists(UserProfileViewModel viewModel, string sort)
        {
            try
            {
                SetBaseUserProfile(viewModel);
                var sortSelection = ApplicationHtmlHelper.BuildSortSelection(sort);
                viewModel.SortSelectionSelected = sortSelection.SingleOrDefault(s => s.IsSelected);
                viewModel.SortSelectionsNotSelected = sortSelection.Where(s => !s.IsSelected).ToList();
            }
            catch (Exception ex)
            {

            }
            return View(viewModel);
        }

        public ActionResult UserProfileFollowing(UserProfileFollowingReferralsViewModel viewModel)
        {
            try
            {
                SetBaseUserProfile(viewModel);
                viewModel.UserProfileFollowingReferrals = _referralService.GetUserProfileFollowingReferrals(viewModel.UserProfileOwner.Id);
            }
            catch (Exception ex)
            {

            }
            return View(viewModel);
        }

        public ActionResult UserProfileFollowingReferralLists(UserProfileFollowingReferralListsViewModel viewModel)
        {
            try
            {
                SetBaseUserProfile(viewModel);
                viewModel.ReferralListFollowerRelationships = _referralListFollowerRelationshipService.GetRelationshipsByFollowerID(viewModel.UserProfileOwner.Id);
            }
            catch (Exception ex)
            {

            }
            return View(viewModel);
        }

        public ActionResult UserProfileFollowingTags(UserProfileFollowingTagsViewModel viewModel)
        {
            try
            {
                SetBaseUserProfile(viewModel);
                viewModel.TagFollowerRelationships = _tagFollowerService.GetRelationshipsByFollowerID(viewModel.UserProfileOwner.Id);
            }
            catch (Exception ex)
            {

            }
            return View(viewModel);
        }

        public ActionResult UserProfileFollowingPeople(UserProfileFollowingPeopleViewModel viewModel)
        {
            try
            {
                SetBaseUserProfile(viewModel);
                viewModel.LeaderFollowerRelationships = _leaderFollowerRelationshipService.GetRelationshipsByFollowerID(viewModel.UserProfileOwner.Id);
            }
            catch (Exception ex)
            {

            }
            return View(viewModel);
        }

        public ActionResult UserProfileReferralDetails(int referralId)
        {
            ReferralDetailsViewModel viewModel = new ReferralDetailsViewModel();
            try
            {
                SetBaseUserProfile(viewModel);
                viewModel.Referral = _referralService.GetReferralById(referralId.ToString());
            }
            catch (Exception ex)
            {

            }
            return View(viewModel);
        }

        public ActionResult UserProfileListDetails(int listId)
        {
            ReferralListDetailsViewModel viewModel = new ReferralListDetailsViewModel();
            try
            {
                SetBaseUserProfile(viewModel);
                viewModel.ReferralList = _referralListService.GetReferralListById(listId);
                viewModel.ReferralListIsFollowedByCurrentUser = _referralListFollowerRelationshipService.Exists(viewModel.ReferralList.ReferralListID);
            }
            catch (Exception ex)
            {

            }
            return View(viewModel);
        }

        public ActionResult UserProfileAbout(UserProfileViewModel viewModel)
        {
            try
            {
                SetBaseUserProfile(viewModel);
            }
            catch (Exception ex)
            {

            }
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult UserProfileFollow(string userName)
        {
            try
            {
                _leaderFollowerRelationshipService.CreateLeaderFollowerRelationship(userName);
                return Json(new { success = true, responseFoo = string.Format("Followed {0} succesfully", userName), JsonRequestBehavior.AllowGet });
            }
            catch (Exception ex)
            {

            }
            return View();
        }

        [HttpPost]
        public ActionResult UserProfileUnfollow(string userName)
        {
            try
            {
                _leaderFollowerRelationshipService.DeleteLeaderFollowerRelationship(userName);
                return Json(new { success = true, responseFoo = string.Format("Unfollowed {0} succesfully", userName), JsonRequestBehavior.AllowGet });
            }
            catch (Exception ex)
            {

            }
            return View();
        }

        public ActionResult LoadReferrals(int pageIndex, int pageSize, string userName, UserProfileViewModel viewModel, string sort)
        {
            viewModel.UserProfileOwner = ApplicationUserHelper.GetUserByUserName(userName);
            var nextPageIndex = pageIndex + 1;
            var userProfileReferrals = _referralService.GetReferralsByUserIdCreatedBy(viewModel.UserProfileOwner.Id, sort);
            var referralCountToLoadNextPage = userProfileReferrals.Skip(nextPageIndex * pageSize)
                         .Take(pageSize).Count();
            viewModel.Referrals = userProfileReferrals.Skip(pageIndex * pageSize)
                         .Take(pageSize).ToList();
            if (referralCountToLoadNextPage <= 0)
            {
                viewModel.NoReferralsLeft = true;
            }
            return Json(
                new
                {
                    noReferralsLeft = viewModel.NoReferralsLeft,
                    partialHtml = RenderRazorViewToString("~/Views/UserProfile/_ReferralsToLoad.cshtml", viewModel)
                },
                JsonRequestBehavior.AllowGet);
        }

        public ActionResult LoadReferralLists(int pageIndex, int pageSize, string userName, UserProfileViewModel viewModel, string sort)
        {
            viewModel.UserProfileOwner = ApplicationUserHelper.GetUserByUserName(userName);
            var nextPageIndex = pageIndex + 1;
            var referralLists = _referralListService.GetReferralListsByUserIdCreatedBy(viewModel.UserProfileOwner.Id, sort);
            var referralListsCountToLoadNextPage = referralLists.Skip(nextPageIndex * pageSize)
                         .Take(pageSize).Count();
            viewModel.ReferralLists = referralLists.Skip(pageIndex * pageSize)
                         .Take(pageSize)
                         .ToList(); 
            if (referralListsCountToLoadNextPage <= 0)
            {
                viewModel.NoReferralListsLeft = true;
            }
            return Json(
            new
            {
                noReferralListsLeft = viewModel.NoReferralListsLeft,
                partialHtml = RenderRazorViewToString("~/Views/UserProfile/_ReferralListsToLoad.cshtml", viewModel)
            },
            JsonRequestBehavior.AllowGet);
        }

        #region Methods
        private void SetBaseUserProfile(BaseUserProfileViewModel viewModel)
        {
            viewModel.UserProfileOwner = _userService.GetUserProfileOwnerFromUrl(Request);
            viewModel.FollowingUser = _leaderFollowerRelationshipService.CurrentUserIsFollowingUser(viewModel.UserProfileOwner.Id);
            var profilePhoto = viewModel.UserProfileOwner.FilePaths.FirstOrDefault(o => o.FileType == Entities.FileType.UserProfilePhoto);
            if (profilePhoto != null)
            {
                if (!System.IO.File.Exists(Path.Combine(@"C:\Users\kevin_000\Desktop\Projects\ReferralApp\ReferralApp\Content\Images", profilePhoto.FileName)))
                    profilePhoto = null;
            }
            viewModel.UserProfilePhotoFileName = profilePhoto != null ? profilePhoto.FileName : "";
        }

ReferralApp/Views/UserProfile/UserProfileAbout.cshtml
@model ReferralApp.Models.UserProfileViewModel
@{
    ViewBag.Title = Model.UserProfileOwner.UserName;
}
@Html.Partial("~/Views/UserProfile/_UserProfilePartial.cshtml")
&nbsp;

MY ABOUT PAGE

ReferralApp/Views/UserProfile/UserProfileFollowing.cshtml
@model ReferralApp.Models.UserProfileFollowingReferralsViewModel
@{
    ViewBag.Title = Model.UserProfileOwner.UserName;
}

@Html.Partial("~/Views/UserProfile/_UserProfilePartial.cshtml")
&nbsp;
@Html.Partial("~/Views/UserProfile/_UserProfileFollowingPartial.cshtml")

@if (Model.UserProfileFollowingReferrals.Count() > 0)
{
    <div>
        @Html.Partial("_Referrals", Model.UserProfileFollowingReferrals)
    </div>
}
else
{
    <p>Following no referrals.</p>
}

ReferralApp/Views/UserProfile/UserProfileFollowingPeople.cshtml
@model ReferralApp.Models.UserProfileFollowingPeopleViewModel
@{
    ViewBag.Title = Model.UserProfileOwner.UserName;
}
<style type="text/css">
    .user-leader-container {
        text-align:center;
        margin-bottom:1em;
    }
    .profile-photo {
        border:1px solid lightgray;
        width:130px;
        height:143px;
    }
    .profile-photo-none {
        font-size:10em;
        color:#555555;
    }
    .username-region {
        font-weight:bold; 
        font-size:x-large;
    }
</style>

@Html.Partial("~/Views/UserProfile/_UserProfilePartial.cshtml")
&nbsp;
@Html.Partial("~/Views/UserProfile/_UserProfileFollowingPartial.cshtml")

@foreach (var relationship in Model.LeaderFollowerRelationships)
{
    <div class="col-lg-3 user-leader-container">
        <a href="/@relationship.UserLeader.UserName">
            @{
                var profilePhoto = relationship.UserLeader.FilePaths.FirstOrDefault(o => o.FileType == ReferralApp.Entities.FileType.UserProfilePhoto);
                if (profilePhoto != null)
                {
                    if (!System.IO.File.Exists(Path.Combine(@"C:\Users\kevin_000\Desktop\Projects\ReferralApp\ReferralApp\Content\Images", profilePhoto.FileName)))
                    {
                        profilePhoto = null;
                    }
                }

                var profilePhotoFileName = profilePhoto != null ? profilePhoto.FileName : "";
            }
            @if (!string.IsNullOrEmpty(profilePhotoFileName))
            {
                <img src="@Url.Content("~/Content/Images/" + profilePhotoFileName)" class="img-circle profile-photo"/>
            }
            else
            {
                <span class="glyphicon glyphicon-user profile-photo-none"></span>
            }
            <div class="username-region">
                @relationship.UserLeader.UserName
            </div>
        </a>
        <div class="follow-btn-container">
            <button class="btn btn-default follow-user" type="submit" value="@relationship.UserLeader.UserName"><span>Unfollow</span></button>
        </div>
        &nbsp;
    </div>
}

<script type="text/javascript">
    $(document).ready(function () {
        $(".follow-btn-container").on("click", ".follow-user", function () {
            var userNameFollow = $(this).val();
            var buttonToSelect = "button[value=" + userNameFollow + "]";
            var targetText = $(event.target).text().trim();
            if (targetText === "Follow") {
                FollowUser(userNameFollow, buttonToSelect);
            }
            else if (targetText === "Unfollow") {
                UnfollowUser(userNameFollow, buttonToSelect);
            }
        });
    });

    function FollowUser(userNameFollow, buttonToSelect)
    {
        $.ajax({
            type: 'POST',
            url: "@Url.Action("UserProfileFollow", "UserProfile")",
            data: {'userName': userNameFollow},
            success: function (response) {
                $(buttonToSelect).replaceWith('<button class="btn btn-default follow-user" type="submit" value='+ userNameFollow +'><span>Unfollow</span></button>');
            },
            error: function (exception) {
                alert('Exception:' + exception);
            }
        });
        return false;
    }

    function UnfollowUser(userNameUnfollow, buttonToSelect)
    {
        $.ajax({
            type: 'POST',
            url: "@Url.Action("UserProfileUnfollow", "UserProfile")",
            data: { 'userName': userNameUnfollow },
            success: function (response) {
                $(buttonToSelect).replaceWith('<button class="btn btn-primary follow-user" type="submit" value=' + userNameUnfollow + '><span>Follow</span></button>');
            },
            error: function (exception) {
                alert('Exception:' + exception);
            }
        });
        return false;
    }
</script>

ReferralApp/Views/UserProfile/UserProfileFollowingReferralLists.cshtml
@model ReferralApp.Models.UserProfileFollowingReferralListsViewModel
@{
    ViewBag.Title = Model.UserProfileOwner.UserName;
}

@Html.Partial("~/Views/UserProfile/_UserProfilePartial.cshtml")
&nbsp;
@Html.Partial("~/Views/UserProfile/_UserProfileFollowingPartial.cshtml")

<div>
    @Html.Partial("_ReferralLists", Model.ReferralListFollowerRelationships.Select(o => o.ReferralList).ToList())
</div>

ReferralApp/Views/UserProfile/UserProfileFollowingTags.cshtml
@model ReferralApp.Models.UserProfileFollowingTagsViewModel
@{
    ViewBag.Title = Model.UserProfileOwner.UserName;
}

@Html.Partial("~/Views/UserProfile/_UserProfilePartial.cshtml")
&nbsp;
@Html.Partial("~/Views/UserProfile/_UserProfileFollowingPartial.cshtml")

@foreach (var relationship in Model.TagFollowerRelationships)
{
    <a href="/tags/@relationship.Tag.Name.ToLower()" class="btn btn-primary btn-sm">
        @relationship.Tag.Name
    </a>
}

ReferralApp/Views/UserProfile/UserProfileHome.cshtml
@model ReferralApp.Models.UserProfileViewModel
@{
    ViewBag.Title = Model.UserProfileOwner.UserName;
}
<style>
    .create-referral-list-form {
        display: none;
    }

    .scrollable-menu {
        height: auto;
        max-height: 200px;
        overflow-x: hidden;
    }

    #results-filter {
        position: relative;
        display: block;
        padding: 10px 15px;
    }
</style>

@Html.Partial("~/Views/UserProfile/_UserProfilePartial.cshtml")
&nbsp;


<h2>Recent</h2>
<hr />
<h2>New Linkcodes</h2>
<hr />
<h2>New Linkcodelists</h2>
<hr />

ReferralApp/Views/UserProfile/UserProfileReferralDetails.cshtml
@using ReferralApp.Models
@model ReferralApp.Models.ReferralDetailsViewModel
@{
    ViewBag.Title = Model.UserProfileOwner.UserName;
    LayoutMenuViewModel LayoutMenuModel = ViewBag.LayoutMenuModel;
}

@Html.Partial("~/Views/UserProfile/_UserProfilePartial.cshtml")
<!-- Modal -->
<div class="modal" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">@Model.Referral.Title</h4>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(window).load(function(){
        $('#myModal').modal('show');
    });
    $('#myModal').on('hidden.bs.modal', function (e) {
        window.location.href =  '/@Model.UserProfileOwner.UserName/linkcodes';
    })
</script>

ReferralApp/Views/UserProfile/UserProfileReferralLists.cshtml
@model ReferralApp.Models.UserProfileViewModel
@{
    ViewBag.Title = Model.UserProfileOwner.UserName;
}
<style type="text/css">
    .create-referral-list-form {
        display: none;
    }
    .scrollable-menu {
        height: auto;
        max-height: 200px;
        overflow-x: hidden;
    }
    #results-filter {
        position: relative;
        display: block;
        padding: 10px 15px;
    }
    .myClickableThingy {
        cursor: pointer;
    }
    #sort-referral-list-region {
        text-align:right; 
        display:none;
    }
    #progress {
        display:none; 
        text-align:center
    }
    #load-more-button {
        display:none;
        margin:auto;
    }
    #load-more-region {
        text-align:center;
    }
</style>


@Html.Partial("~/Views/UserProfile/_UserProfilePartial.cshtml")
&nbsp;
<div id="container">
    <div id="sort-referral-list-region">
        <form id="form-sort-referrals" action="~/@Model.UserProfileOwner.UserName/" method="get">
            <input type="hidden" name="sort" id="sort-referral-value" />
            <div class="btn-group">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    <span class="selection">@Model.SortSelectionSelected.Text</span> <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                    @foreach (var sortNotSelected in Model.SortSelectionsNotSelected)
                    {
                        if (!sortNotSelected.Value.Contains("archived"))
                        {
                            <li><a class="myClickableThingy" data-value="@sortNotSelected.Value">@sortNotSelected.Text</a></li>
                        }
                    }
                </ul>
            </div>
        </form>
    </div>
    &nbsp;
</div>
&nbsp;
<div id="progress">
    <h4>Loading...</h4>
</div>
<div id="load-more-region">
    <button id="load-more-button">
        <h4>load more</h4>
    </button>
</div>



<script type="text/javascript">
    var pageSize = 30;
    var pageIndex = 0;
    var userName = '@Model.UserProfileOwner.UserName';
    var noReferralListsLeft = false;
    var sortSelected = '@Model.SortSelectionSelected.Value';
    $(document).ready(function () {
        GetData();
        $("#load-more-button").on("click", function () {
            GetData();
        });

        $(".dropdown-menu li a.myClickableThingy").click(function () {
            $('#sort-referral-value').val($(this).data('value'));
            var initialText = $(this).parents(".btn-group").find('.selection').text();
            $(this).parents(".btn-group").find('.selection').text($(this).text());
            $(this).text(initialText);
            $('#form-sort-referrals').submit();
        });
    });

    function GetData() {
        $.ajax({
            type: 'GET',
            url: "@Url.Action("LoadReferralLists", "UserProfile")",
            data: { "pageindex": pageIndex, "pagesize": pageSize, "userName": userName, "sort": sortSelected },
            dataType: 'json',
            success: function (data) {
                noReferralListsLeft = data.noReferralListsLeft;
                if (data != null) {
                    $("#container").append(data.partialHtml);
                    pageIndex++;
                }
                else {
                    alert("data is null");
                }
            },
            beforeSend: function () {
                $("#load-more-button").hide();
                $("#progress").show();
            },
            complete: function (data) {
                $("#progress").hide();
                $("#sort-referral-list-region").show();

                if (!noReferralListsLeft) {
                    $("#load-more-button").show();
                }
                else {
                    $("#load-more-button").hide();
                }
            },
            error: function () {
                alert("Error while retrieving data!");
            }
        });
    }
    //$(function () {

    //    $('.create-referral-list').click(function () {
    //        $(this).children("a").remove();
    //        $(this).removeClass("create-referral-list");
    //        $(this).children(".create-referral-list-form").show();
    //    })

    //    $('.create-referral-list-btn').prop('disabled', true);
    //    $('#new-referral-list-title').keyup(function () {
    //        $('.create-referral-list-btn').prop('disabled', this.value == "" ? true : false);
    //    })
    //})

    //$('.stop-propagation').on('click', function (e) {
    //    e.stopPropagation();
    //});
</script>

ReferralApp/Views/UserProfile/UserProfileReferrals.cshtml
@using ReferralApp.Models
@model ReferralApp.Models.UserProfileViewModel
@{
    LayoutMenuViewModel LayoutMenuModel = ViewBag.LayoutMenuModel;
    ViewBag.Title = Model.UserProfileOwner.UserName;
}
<style>
    #results-filter {
        position: relative;
    display: block;
    padding: 10px 15px;
    }

    .myClickableThingy {
    cursor: pointer;
    }
    #sort-referrals-region {
        text-align:right; 
        display:none;
    }
    #progress {
        display:none; 
        text-align:center
    }
    #load-more-button {
        display:none;
        margin:auto;
    }
    #load-more-region {
        text-align:center;
    }
</style>

@Html.Partial("~/Views/UserProfile/_UserProfilePartial.cshtml")
&nbsp;
<div id="container">
    <div id="sort-referrals-region">
        <form id="form-sort-referrals" action="~/@Model.UserProfileOwner.UserName/linkcodes" method="get">
            <input type="hidden" name="sort" id="sort-referral-value" />
            <div class="btn-group">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    <span class="selection">@Model.SortSelectionSelected.Text</span> <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                    @foreach (var sortNotSelected in Model.SortSelectionsNotSelected)
                    {
                        if (sortNotSelected.Value.Contains("archived"))
                        {
                            if (LayoutMenuModel.CurrentUser != null && LayoutMenuModel.CurrentUser.UserName.Equals(Model.UserProfileOwner.UserName))
                            {
                                <li><a class="myClickableThingy" data-value="@sortNotSelected.Value">@sortNotSelected.Text</a></li>
                            }
                        }
                        else
                        {
                            <li><a class="myClickableThingy" data-value="@sortNotSelected.Value">@sortNotSelected.Text</a></li>
                        }
                    }
                </ul>
            </div>
        </form>
    </div>
    &nbsp;
</div>
&nbsp;
<div id="progress">
    <h4>Loading...</h4>
</div>
<div id="load-more-region">
    <button id="load-more-button">
        <h4>load more</h4>
    </button>
</div>

<script type="text/javascript">
    var pageSize = 30;
    var pageIndex = 0;
    var userName = '@Model.UserProfileOwner.UserName';
    var noReferralsLeft = false;
    var sortSelected = '@Model.SortSelectionSelected.Value';
    $(document).ready(function () {
        GetData();
        $("#load-more-button").on("click", function () {
            GetData();
        });

        $(".dropdown-menu li a.myClickableThingy").click(function () {
            $('#sort-referral-value').val($(this).data('value'));
            var initialText = $(this).parents(".btn-group").find('.selection').text();
            $(this).parents(".btn-group").find('.selection').text($(this).text());
            $(this).text(initialText);
            $('#form-sort-referrals').submit();
        });
    });

    function GetData() {
        $.ajax({
            type: 'GET',
            url: "@Url.Action("LoadReferrals", "UserProfile")",
            data: { "pageindex": pageIndex, "pagesize": pageSize, "userName": userName, "sort": sortSelected },
            dataType: 'json',
            success: function (data) {
                noReferralsLeft = data.noReferralsLeft;
                if (data != null) {
                    $("#container").append(data.partialHtml);
                    pageIndex++;
                }
                else {
                    alert("data is null");
                }
            },
            beforeSend: function () {
                $("#load-more-button").hide();
                $("#progress").show();
            },
            complete: function (data) {
                $("#progress").hide();
                $("#sort-referrals-region").show();

                if (!noReferralsLeft) {
                    $("#load-more-button").show();
                }
                else {
                    $("#load-more-button").hide();
                }
            },
            error: function () {
                alert("Error while retrieving data!");
            }
        });
    }
</script>

ReferralApp/Views/UserProfile/_ReferralListsToLoad.cshtml
@using ReferralApp.Models
@model UserProfileViewModel
@{
    LayoutMenuViewModel LayoutMenuModel = ViewBag.LayoutMenuModel;
}

@if (Model.ReferralLists.Count() > 0)
{
    <div class="row">
        @Html.Partial("_ReferralLists", Model.ReferralLists)
    </div>
}
else
{
    <p>No referral lists created.</p>
    if (LayoutMenuModel.CurrentUser != null && LayoutMenuModel.CurrentUser.UserName.Equals(Model.UserProfileOwner.UserName))
    {
        <a href="@Url.Action("Create", "ReferralList")">create a linkcode...</a>
    }
}

ReferralApp/Views/UserProfile/_ReferralsToLoad.cshtml
@using ReferralApp.Models
@model UserProfileViewModel
@{
    LayoutMenuViewModel LayoutMenuModel = ViewBag.LayoutMenuModel;
}

@if (Model.Referrals.Count() > 0)
{
    <div>
        @Html.Partial("_Referrals", Model.Referrals)
    </div>
}
else
{
    <p>No referrals created.</p>
    if (LayoutMenuModel.CurrentUser != null && LayoutMenuModel.CurrentUser.UserName.Equals(Model.UserProfileOwner.UserName))
    {
        <a href="@Url.Action("Create", "Referral")" >create a linkcode...</a>
    }
}

ReferralApp/Views/UserProfile/_UserProfileFollowingPartial.cshtml
@using ReferralApp.Helpers

<div class="row">
    <ul class="nav nav-pills">
        <li role="presentation" class="@Html.IsSelected(actions: "UserProfileFollowingReferralLists", controllers: "UserProfile", cssClass: "active")"><a href="/@Model.UserProfileOwner.UserName/following">Linkcodelists</a></li>
        <li role="presentation" class="@Html.IsSelected(actions: "UserProfileFollowing", controllers: "UserProfile", cssClass: "active")"><a href="/@Model.UserProfileOwner.UserName/following/linkcodes">Linkcodes</a></li>
        <li role="presentation" class="@Html.IsSelected(actions: "UserProfileFollowingTags", controllers: "UserProfile", cssClass: "active")"><a href="/@Model.UserProfileOwner.UserName/following/tags">Tags</a></li>
        <li role="presentation" class="@Html.IsSelected(actions: "UserProfileFollowingPeople", controllers: "UserProfile", cssClass: "active")"><a href="/@Model.UserProfileOwner.UserName/following/people">People</a></li>
    </ul>
</div>
<hr>