ReferralApp/Entities/Referral.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ReferralApp.Models;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace ReferralApp.Entities
{
    public class Referral : BaseReferral
    {
        public int ReferralID { get; set; }
        [Required]
        public string Url { get; set; }
        public string Code { get; set; }
        public virtual ICollection<ReferralListRelationship> ReferralListRelationships { get; set; }
        public virtual ICollection<TagReferralRelationship> TagReferralRelationships { get; set; }
        public virtual ICollection<ReferralAnalytics> ReferralAnalytics { get; set; }
    }
}

ReferralApp/Models/ReferralViewModel.cs
using ReferralApp.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ReferralApp.Models
{
    public class ReferralViewModel
    {
        public Referral Referral { get; set; }
        public ReferralList ReferralList { get; set; }
        public List<Referral> Referrals { get; set; }
        public List<ReferralList> ReferralLists { get; set; }
        public List<ReferralListRelationship> ReferralListRelationship { get; set; }
    }
}

ReferralApp/Controllers/ReferralController.cs
using ReferralApp.DAL;
using ReferralApp.Models;
using System;
using System.Linq;
using System.Web.Mvc;
using ReferralApp.Helpers;
using ReferralApp.Services;

namespace ReferralApp.Controllers
{
    public class ReferralController : BaseController
    {
        private ReferralService _referralService;
       
        public ReferralController()
        {
            _referralService = new ReferralService();
        }

        [Authorize]
        public ActionResult Create()
        {
            CreateReferralViewModel viewmodel = new CreateReferralViewModel();
            return View(viewmodel);
        }

        //TODO: add tags input for (cateogry and tags)
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateReferralViewModel viewModel, string tags)
        {
            var user = ApplicationUserHelper.GetCurrentUser();
            try
            {
                //http://stackoverflow.com/questions/15333513/why-modelstate-isvalid-always-return-false-in-mvc
                //var errors = ModelState.Values.SelectMany(v => v.Errors);

                if (ModelState.IsValid)
                {
                    viewModel.Referral.UserIdCreatedBy = user.Id;
                    _referralService.Save(viewModel.Referral);
                    if (!string.IsNullOrEmpty(tags))
                    {
                        _referralService.AddTags(viewModel.Referral, tags);
                    }
                    return Redirect("/" + user.UserName);
                }
            }
            catch (Exception ex)
            {
                return View("Error");
            }
            return View();
        }

        [HttpPost]
        public ActionResult Archive(int referralID)
        {
            try
            {
                _referralService.Archive(referralID);
                return Json(new { });
            }
            catch (Exception ex)
            {

            }
            return View();
        }
    }
}

ReferralApp/Controllers/TagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ReferralApp.Models;
using ReferralApp.Services;

namespace ReferralApp.Controllers
{
    public class TagController : BaseController
    {
        private TagService _tagService;
        private ReferralService _referralService;
        private ReferralListService _referralListService;
        private TagFollowerService _tagFollowerService;

        public TagController()
        {
            _tagService = new TagService();
            _referralService = new ReferralService();
            _referralListService = new ReferralListService();
            _tagFollowerService = new TagFollowerService();
        }
        // GET: Tag
        public ActionResult Index()
        {
            TagIndexViewModel model = new TagIndexViewModel();
            model.Tags = _tagService.GetAllTags();
            return View(model);
        }

        public ActionResult TagDetails(string tagName)
        {
            TagDetailsViewModel model = new TagDetailsViewModel();
            model.Tag = _tagService.GetTagByName(tagName);
            model.TagReferrals = _tagService.GetTagReferrals(model.Tag.TagID);
            model.CurrentUserIsFollowingTag = _tagFollowerService.Exists(model.Tag.TagID);
            return View(model);
        }

        public ActionResult GetTagNames()
        {
            var tagNames = _tagService.GetAllTags().OrderBy(o => o.Name).Select(o => o.Name);
            return Json(new { tagNames = tagNames }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult FollowTag(int tagID)
        {
            _tagFollowerService.Create(tagID);
            return Json(new object { });
        }

        [HttpPost]
        public ActionResult UnfollowTag(int tagID)
        {
            _tagFollowerService.Delete(tagID);
            return Json(new object { });
        }
    }
}

ReferralApp/Views/Referral/Create.cshtml
@model ReferralApp.Models.CreateReferralViewModel
@{
    ViewBag.Title = "Create your Referral";
}
@*<head>
    <script type="text/javascript" src="@Url.Content("~/Scripts/bootstrap-tagsinput.min.js")"></script>
    <link rel="stylesheet" href="@Url.Content("~/Content/bootstrap-tagsinput.css")" type="text/css" />
</head>*@
@*<script src="@Url.Content("~/Scripts/bloodhound.min.js")" type="text/javascript"></script>*@

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Create", "Referral", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
 
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.Referral.Title, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Referral.Title, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Referral.Title)
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Link", new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Referral.Url, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Referral.Code, new { @class = "col-md-2 control-label" }) 
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Referral.Code, new { @class = "form-control", })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Referral.Description, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextAreaFor(m => m.Referral.Description, new { @class = "form-control", })
        </div>
    </div>
    @*<div class="form-group">
        @Html.LabelFor(m => m.Referral.CategoryReferralRelationships, new { @class = "col-md-2 control-label" })
        <div class="col-md-10" data-role="tagsinput">
            <input type="text" id="categories-input"  name="categories" />
        </div>
    </div>*@
    <div class="form-group">
        @Html.Label("Tags", new { @class = "col-md-2 control-label" })
        <div class="col-md-10" data-role="tagsinput">
            <input type="text" id="tags-input" name="tags" />
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Referral.ExpirationDate, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Referral.ExpirationDate, new { @class = "form-control", id = "expirationDate", placeholder = "mm/dd/yyyy" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-primary" value="Create" />
        </div>
    </div>
    
}

<script type="text/javascript">
    $(function () {
        var tagNames = new Bloodhound({
            datumTokenizer: Bloodhound.tokenizers.whitespace,
            queryTokenizer: Bloodhound.tokenizers.whitespace,
            remote: {
                url: '@Url.Action("GetTagNames", "Tag")',
                transform: function (response) {
                    return $.map(response.tagNames, function (tag) {
                        return {
                            name: tag
                        };
                    });
                },
                cache: false
            }
        });

        $('#tags-input').tagsinput({
            typeaheadjs: [{
                minLength: 1,
                highlight: true,
            }, {
                minlength: 3,
                name: 'tagNames',
                displayKey: 'name',
                valueKey: 'name',
                source: tagNames
            }],
            freeInput: true
        });

        $('.bootstrap-tagsinput').keypress(function (e) {
            if (e.which == 13) return false;
            //or...
            if (e.which == 13) e.preventDefault();
        });
        
        $('#expirationDate').datetimepicker();
    });
</script>