ReferralApp/Entities/Referral.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ReferralApp.Models;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace ReferralApp.Entities
{
    public class Referral : BaseReferral
    {
        public int ReferralID { get; set; }
        [Required]
        public string Url { get; set; }
        public string Code { get; set; }
        public virtual ICollection<ReferralListRelationship> ReferralListRelationships { get; set; }
        public virtual ICollection<TagReferralRelationship> TagReferralRelationships { get; set; }
        public virtual ICollection<ReferralAnalytics> ReferralAnalytics { get; set; }
    }
}

ReferralApp/Entities/ReferralList.cs
using ReferralApp.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ReferralApp.Entities
{
    public class ReferralList : BaseReferral
    {
        public int ReferralListID { get; set; }
        public virtual ICollection<ReferralListRelationship> ReferralListRelationships { get; set; }
        public virtual ICollection<CategoryReferralListRelationship> CategoryReferralListRelationships { get; set; }
        public virtual ICollection<TagReferralListRelationship> TagReferralListRelationships { get; set; }
        public virtual ICollection<ReferralListFollowerRelationship> ReferralListFollowerRelationships { get; set; }
        public virtual ICollection<ReferralListAnalytics> ReferralListAnalytics { get; set; }
    }
}

ReferralApp/Models/ReferralListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ReferralApp.Entities;

namespace ReferralApp.Models
{
    public class ReferralListViewModel
    {
        public ReferralList ReferralList { get; set; }
        public List<ReferralList> ReferralLists { get; set; }
    }
}

ReferralApp/Models/ReferralListsAddToViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ReferralApp.Entities;
namespace ReferralApp.Models
{
    public class ReferralListsAddToViewModel
    { 
        public Referral Referral { get; set; }
        public List<ReferralList> ReferralLists { get; set; }
    }
}

ReferralApp/Models/ReferralViewModel.cs
using ReferralApp.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ReferralApp.Models
{
    public class ReferralViewModel
    {
        public Referral Referral { get; set; }
        public ReferralList ReferralList { get; set; }
        public List<Referral> Referrals { get; set; }
        public List<ReferralList> ReferralLists { get; set; }
        public List<ReferralListRelationship> ReferralListRelationship { get; set; }
    }
}

ReferralApp/Controllers/ReferralController.cs
using ReferralApp.DAL;
using ReferralApp.Models;
using System;
using System.Linq;
using System.Web.Mvc;
using ReferralApp.Helpers;
using ReferralApp.Services;

namespace ReferralApp.Controllers
{
    public class ReferralController : BaseController
    {
        private ReferralService _referralService;
       
        public ReferralController()
        {
            _referralService = new ReferralService();
        }

        [Authorize]
        public ActionResult Create()
        {
            CreateReferralViewModel viewmodel = new CreateReferralViewModel();
            return View(viewmodel);
        }

        //TODO: add tags input for (cateogry and tags)
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateReferralViewModel viewModel, string tags)
        {
            var user = ApplicationUserHelper.GetCurrentUser();
            try
            {
                //http://stackoverflow.com/questions/15333513/why-modelstate-isvalid-always-return-false-in-mvc
                //var errors = ModelState.Values.SelectMany(v => v.Errors);

                if (ModelState.IsValid)
                {
                    viewModel.Referral.UserIdCreatedBy = user.Id;
                    _referralService.Save(viewModel.Referral);
                    if (!string.IsNullOrEmpty(tags))
                    {
                        _referralService.AddTags(viewModel.Referral, tags);
                    }
                    return Redirect("/" + user.UserName);
                }
            }
            catch (Exception ex)
            {
                return View("Error");
            }
            return View();
        }

        [HttpPost]
        public ActionResult Archive(int referralID)
        {
            try
            {
                _referralService.Archive(referralID);
                return Json(new { });
            }
            catch (Exception ex)
            {

            }
            return View();
        }
    }
}

ReferralApp/Controllers/ReferralListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ReferralApp.DAL;
using ReferralApp.Models;

using ReferralApp.Helpers;
using ReferralApp.Services;

namespace ReferralApp.Controllers
{
    public class ReferralListController : BaseController
    {
        private ReferralService _referralService;
        private ReferralListService _referralListService;
        private ReferralListRelationshipService _referralListRelationshipService;
        private ReferralListFollowerRelationshipService _referralListFollowerRelationshipService;

        public ReferralListController()
        {
            _referralService = new ReferralService();
            _referralListService = new ReferralListService();
            _referralListRelationshipService = new ReferralListRelationshipService();
            _referralListFollowerRelationshipService = new ReferralListFollowerRelationshipService();
        }

        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult Create(CreateReferralListViewModel viewModel, string referralID, string tags, string listTitle)
        {
            var user = ApplicationUserHelper.GetCurrentUser();
            //CreateReferralListViewModel viewModel = new CreateReferralListViewModel();
            try
            {
                if (ModelState.IsValid)
                {
                    if (viewModel.ReferralList == null)
                    {
                        //viewModel = new CreateReferralListViewModel();
                        //viewModel.ReferralList = new ReferralList();
                        //viewModel.ReferralList.Title = listTitle;
                        _referralListService.CreateReferralList(viewModel, listTitle, user.Id);
                    }
                    else
                    {
                        viewModel.ReferralList.UserIdCreatedBy = user.Id;
                        _referralListService.CreateReferralList(viewModel.ReferralList);
                    }
                    
                    
                    if (!string.IsNullOrEmpty(referralID))
                    {
                        _referralListRelationshipService.Create(referralID, viewModel.ReferralList.ReferralListID.ToString());
                        return Redirect(Request.UrlReferrer.LocalPath);
                    }
                    if (!string.IsNullOrEmpty(tags))
                    {
                        _referralListService.AddTags(viewModel.ReferralList, tags);
                    }
                }
            }
            catch(Exception ex)
            {

            }
            return Redirect(string.Format("/{0}/lists/{1}", user.UserName, viewModel.ReferralList.ReferralListID));
        }

        [HttpPost]
        public ActionResult AddReferralToList(string referralID, string referralListID)
        {
            _referralListRelationshipService.Create(referralID, referralListID);
            return Json(new object { });
        }

        [HttpPost]
        public ActionResult RemoveReferralFromList(string referralID, string referralListID)
        {
            _referralListRelationshipService.Delete(referralID, referralListID);
            return Json(new object { });
        }

        public ActionResult GetReferralListsCurrentUser(string referralID)
        {
            ReferralListsAddToViewModel viewModel = new ReferralListsAddToViewModel();
            viewModel.Referral = _referralService.GetReferralById(referralID);
            if (Request.IsAuthenticated)
            {
                viewModel.ReferralLists = _referralListService.GetReferralListsByUserIdCreatedBy(ApplicationUserHelper.GetCurrentUserId().ToString()).ToList();
            }
            return Json(new { partialHtml = RenderRazorViewToString("~/Views/Shared/_ReferralListsAddTo.cshtml", viewModel) }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult SaveReferralList(string referralListID)
        {
            _referralListFollowerRelationshipService.Create(referralListID);
            return Json(new object { });
        }

        [HttpPost]
        public ActionResult UnsaveReferralList(string referralListID)
        {
            _referralListFollowerRelationshipService.Delete(referralListID);
            return Json(new object { });
        }
    }
}

ReferralApp/Views/Shared/_NavBarMenuRightCommon.cshtml
@using ReferralApp.Models
@{
    LayoutMenuViewModel LayoutMenuModel = ViewBag.LayoutMenuModel;
}
<style>
    .myClickableThingy {
        cursor: pointer;
    }
    .btn {
        text-align:left
    }
</style>
<li class="menu-item">
    <p class="navbar-btn">
        <div class="btn-group">
            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="glyphicon glyphicon-plus"></span>
                @*<span class="glyphicon glyphicon-plus"></span> Refer*@
            </button>
            <ul class="dropdown-menu">
                <li><a href="@Url.Action("Create", "Referral")">Create Referral</a></li>
                <li><a href="@Url.Action("Create", "ReferralList")">Create Referral List</a></li>
                @*TODO - make into modals
                    <li><a class="btn" data-toggle="modal" data-target="#myModal">Create Linkcode</a></li>
                <li><a class="btn" data-toggle="modal" data-target="#createLinkcodelist">Create Linkcodelist</a></li>*@
            </ul>
        </div>
    </p>
</li>
<li class="menu-item">
    <div class="navbar-btn">
        <div class="btn-group">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="glyphicon glyphicon-tags"></span>
            </button>
            <ul class="dropdown-menu">
                <li><a href="@Url.Action("Create", "Referral")">Cars</a></li>
                <li><a href="#">Clothes</a></li>
                <li><a href="#">Food</a></li>
                <li><a href="#">Sports</a></li>
                <li><a href="#">Music</a></li>
                <li><a href="/tags"><i>view all...</i></a></li>
            </ul>
        </div>
    </div>
</li>
<li class="menu-item">
    <div class="navbar-btn">
        <div class="btn-group">
            <button type="button" class="btn btn-default button-tooltip" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="glyphicon glyphicon-question-sign"></span>
            </button>
            <ul class="dropdown-menu">
                <li><a href="/about">About</a></li>
                <li><a href="/help">Help</a></li>
                <li><a href="/privacy">Privacy</a></li>
                <li><a href="/blog">Blog</a></li>
            </ul>
        </div>
    </div>
</li>
<script type="text/javascript">
    $(function () {
        $(".button-tooltip").tooltip();
    });
</script>

ReferralApp/Views/Shared/_ReferralLists.cshtml
@using ReferralApp.Models
@model List<ReferralApp.Entities.ReferralList>
@{
    LayoutMenuViewModel LayoutMenuModel = ViewBag.LayoutMenuModel;
}
<style type="text/css">
    .create-referral-list-form {
        display: none;
    }
    .scrollable-menu {
        height: auto;
        max-height: 200px;
        overflow-x: hidden;
    }
    .panel-referral-list {
        width: 100%;
    }
    .referral-list-footer-region {
        position: relative;
    }
    .dropdown-menu-add-to {
        min-width: 300px;
    }

    .referral-lists-region {
        border: 1px solid #ddd;
    }

    .btn-user-options {
        font-size: 2em;
    }
    /*Important:*/
    .link-spanner {
        position: absolute;
        width: 100%;
        height: 100%;
        top: 0;
        left: 0;
        z-index: 1;
        /* edit: fixes overlap error in IE7/8,
         make sure you have an empty gif
      background-image: url('empty.gif');*/
    }
    .username-link {
        color:white; 
        font-weight:bolder; 
        font-style:italic;
    }
    .username-link:hover {
        color:white; 
        font-weight:bolder; 
        font-style:italic;
    }
    .username-link-region {
        float: right;
    }
    .user-action-left {
        float:left
    }
    .user-action-right {
        float:right
    }
</style>

@foreach (var referralList in Model)
{
    int count = referralList.ReferralListRelationships.Count();
    var url = referralList.ReferralListID.ToString();
    var listUrl = string.Format("/{0}/lists/{1}", referralList.CreatedBy.UserName, referralList.ReferralListID);

    <div class="col-lg-6">
        <div class="panel panel-primary panel-referral-list">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-list"></span>
                <b>@Html.DisplayFor(modelItem => referralList.Title)</b>
                <span><i>(@count linkcodes)</i></span>
                <span class="username-link-region">
                   by <a href="/@referralList.CreatedBy.UserName" class="username-link">@referralList.CreatedBy.UserName</a>
                </span>
            </div>
            <div class="panel-body">
                <div>
                    @if (referralList.TagReferralListRelationships.Count > 0)
                    {
                        <span class="glyphicon glyphicon-tags"></span>
                    }
                    &nbsp;
                    @foreach (var r in referralList.TagReferralListRelationships.Take(3))
                    {
                        <span class="label label-warning">@r.Tag.Name</span>
                    }
                </div>
                <div class="referral-list-footer-region">
                    <hr />
                    @*TODO: add auth behavior*@
                    <div class="btn-region-user-action">
                        <div class="user-action-left">
                            <div class="btn-group">
                                <button class="btn btn-default btn-xs">Save</button>
                            </div>
                            <!-- ADD TO -->
                            <div class="btn-group">
                                <button value="" type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <span class="glyphicon glyphicon-plus" value=""></span> Add all to
                                </button>
                                <ul class="dropdown-menu stop-propagation dropdown-menu-add-to">
                                    <li>
                                        <div class="form-group">
                                            <div class="col-md-10">
                                                <input value="@ViewBag.QueryString" type="text" id="Search" name="q" class="form-control" placeholder="Search by referral list title" aria-describedby="sizing-addon2" autocomplete="off" />
                                            </div>
                                        </div>
                                        <br />
                                        <br />
                                        <br />
                                    </li>
                                    <li class="referral-lists-region">
                                        <div class="scrollable-menu referral-lists-container"></div>
                                    </li>
                                    <li class="create-referral-list">
                                        <a>Create referral list</a>
                                        <form action="~/ReferralList/Create" method="post" class="create-referral-list-form">
                                            <div class="form-group">
                                                <div class="col-md-12">
                                                    @*@Html.Hidden("referralID", referral.ReferralID.ToString())*@
                                                    <input type="text" name="listTitle" class="new-referral-list-title form-control" placeholder="Create referral list" value="" />
                                                </div>
                                            </div>
                                            <br />
                                            <br />
                                            <div class="form-group">
                                                <div class="col-md-8">

                                                </div>
                                                <div class="col-md-4">
                                                    <input type="submit" class="btn btn-warning create-referral-list-btn" value="Create" />
                                                </div>
                                            </div>
                                        </form>
                                    </li>
                                </ul>
                            </div>
                            <!--SHARE-->
                            <div class="btn-group">
                                <button class="btn btn-default btn-xs dropdown-toggle dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    share
                                </button>
                                <ul class="dropdown-menu">
                                    <li><a href="@Url.Action("Create", "Referral")">Copy url to linkcode</a></li>
                                    <li><a href="#">Share via messages</a></li>
                                </ul>
                            </div>
                            &nbsp;
                            @if (LayoutMenuModel.CurrentUser != null && referralList.UserIdCreatedBy.Equals(LayoutMenuModel.CurrentUser.Id))
                            {
                            <!-- OPTIONS -->
                                <div class="btn-group">
                                    <span class="glyphicon glyphicon-option-horizontal dropdown-toggle dropdown btn-user-options" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></span>
                                    <ul class="dropdown-menu">
                                        <li><a class="myClickableThingy" data-toggle="modal" data-target="">Edit</a></li>
                                        @*<li><a class="myClickableThingy" data-toggle="modal" data-target="#@referralDeleteID">Archive</a></li>*@
                                        <li><a class="myClickableThingy referral-archive" data-value="">Archive</a></li>
                                    </ul>
                                </div>
                            }
                        </div>
                        <div class="user-action-right">
                            <div class="btn-group">
                                <button class="btn btn-success btn-sm btn-view-list">View List</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <a href="@listUrl">
            <span class="link-spanner"></span>
        </a>
    </div>
}

<script type="text/javascript">
    $(function () {
        $('.referral-archive').on('click', function (e) {
            var referralValue = $(this).data('value');
            console.log(referralValue);
            //$('#referralDelete-' + referralValue).modal('hide');
            //$('#cancel-modal-' + referralValue).click();
            // $('#' + referralValue).remove();
            //TODO archive referral
            ArchiveReferral(referralValue);
        })
        $('.create-referral-list').click(function () {
            $(this).children("a").remove();
            $(this).removeClass("create-referral-list");
            $(this).children(".create-referral-list-form").show();
        })
        $('.create-referral-list-btn').prop('disabled', true);
        $('.new-referral-list-title').keyup(function () {
            $('.create-referral-list-btn').prop('disabled', this.value == "" ? true : false);
        })
    });

    function GetReferralListsCurrentUser(thisObj, referralID)
    {
        $.ajax({
            type: 'GET',
            url: "@Url.Action("GetReferralListsCurrentUser", "ReferralList")",
            data: { "referralID": referralID },
        dataType: 'json',
        success: function (data) {
            $(".referral-lists-container").children('a').remove();
            $(".referral-lists-container").append(data.partialHtml);
        },
        beforeSend: function () {
        },
        complete: function (data) {
        },
        error: function () {
            alert("Error while retrieving data!");
        }
    })
    }

    $('.stop-propagation').on('click', function (e) {
        e.stopPropagation();
    });
</script>

ReferralApp/Views/Shared/_ReferralListsAddTo.cshtml
@model ReferralApp.Models.ReferralListsAddToViewModel

<style type="text/css">
    .referral-remove {
        font-size:12px
    }
</style>

@if (Model.ReferralLists != null && Model.ReferralLists.Count() > 0)
{ //TODO: pass referral id???
    foreach (var referralList in Model.ReferralLists)
    {
        string referralIdAndListId = "";

        if (referralList.ReferralListRelationships.Any(o => o.ReferralID == Model.Referral.ReferralID))
        {
            referralIdAndListId = string.Format("{0},{1}", Model.Referral.ReferralID, referralList.ReferralListID);
            <a data-value="@referralIdAndListId" class="list-group-item">@referralList.Title <i class="referral-remove">(remove)</i></a>
        }
        else
        {
            referralIdAndListId = string.Format("{0},{1}", Model.Referral.ReferralID, referralList.ReferralListID);
            <a data-value="@referralIdAndListId" class="list-group-item">@referralList.Title</a>
        }
    }
}

<script>
    $(document).ready(function () {

        $('a').on('click', function () {

            var anchorReferralList = $(this);
            var anchorReferralListVal =  $(this).data('value').split(',');
            var referralID = anchorReferralListVal[0];
            var referralListID = anchorReferralListVal[1]
           
            if (!anchorReferralList.text().includes("remove")) {
                //alert('add');
                $.ajax({
                    type: 'POST',
                    url: "@Url.Action("AddReferralToList", "ReferralList")",
                    data: { 'referralID': referralID, 'referralListID': referralListID },
                    success: function () {
                        //  alert('success');
                        $('#notification-container').children().remove();
                        $('#notification-container').prepend("<span class='alert alert-dismissible alert-success'><b><span class='glyphicon glyphicon-ok'></span> Added to linkcodelist " + anchorReferralList.text() + "</b></span>").hide();
                    },
                    complete: function () {
                    //    alert("all day");
                    //anchorReferralList.parent('button').attr('aria-expanded', 'false');
                    anchorReferralList.dropdown('toggle');
                        $('#notification-container').show().delay(2000).fadeOut();
                    },
                    error: function () {
                    }
                });
            }
            else {
                //alert('remove');
                $.ajax({
                    type: 'POST',
                    url: "@Url.Action("RemoveReferralFromList", "ReferralList")",
                    data: { 'referralID': referralID, 'referralListID': referralListID },
                    success: function () {
                        //  alert('success');
                        $('#notification-container').children().remove();
                        $('#notification-container').prepend("<span class='alert alert-dismissible alert-success'><b><span class='glyphicon glyphicon-ok'></span> Removed from linkcodelist " + anchorReferralList.text().replace('(remove)', '') + "</b></span>").hide();
                    },
                    complete: function () {
                    //    alert("all day");
                    //anchorReferralList.parent('button').attr('aria-expanded', 'false');
                    anchorReferralList.dropdown('toggle');
                    $('#notification-container').show().delay(2000).fadeOut();
                    },
                    error: function () {
                    }
                });
            }
        })
    });
</script>